#!/usr/bin/env bash
## Configure your domain zone so that the subdomain
## www points to your load-balancer IP (lb-01)

subdomains_info ()
{
	declare -a subdomains=( "www" "lb-01" "web-01" "web-02" )
	#? Validate if exist subdomain.
	for subdomain in "${subdomains[@]}"
	do
		if [ "${2}" == "${subdomain}" ] || [ -z "${2}" ];
		then
			dig "$subdomain.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk -v var="${subdomain}" '{print "The subdomain " var " is a " $7 " record and points to " $8}'
		fi
	done
}

subdomains_info "$1" "$2"