#!/usr/bin/env bash
# script that installs nginx
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chown -R ubuntu /var/www
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo service nginx start
