#!/usr/bin/env bash
# Configure your Nginx server to /redirect_me is redirecting to another page
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=aBt8fN7mJNg&ab_channel=BackstreetBoysVEVO permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
