#!/usr/bin/env bash
# Configure your HAProxy server
sudo apt update -y
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt-get install haproxy=2.4.\* -y
# /etc/haproxy/haproxy.cfg
sudo sed -i "$ a \\nfrontend haproxy-main\n\tbind *:80\n\tdefault_backend nginx_servers" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a \\nbackend nginx_servers\n\tbalance roundrobin\n\tserver web-01 34.148.228.73:80\n\tserver web-02 3.91.201.4:80" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
