#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
if [[ $1 != "start" && $1 != "stop" && $1 != "restart" ]]
then
    echo "Usage: manage_my_process {start|stop|restart}"
fi
if [[ $1 == "start" ]]
then
    ./manage_my_process &
    echo "$$" >> /var/run/my_process.pid
    echo "manage_my_process started"
fi
if [[ $1 == "stop" ]]
then
    kill "$(pgrep -f manage_my_process)"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
fi
if [[ $1 == "restart" ]]
then
    kill "$(pgrep -f manage_my_process)"
    rm -rf /var/run/my_process.pid
    ./manage_my_process &
    echo "$$" >> /var/run/my_process.pid
    echo "manage_my_process restarted"
fi
