#!/usr/bin/env bash
# This script is displaying "Best School" 10 times with while
count=1
while [ $count -le 100 ]
do
    if (( count % 5 == 0 && count % 3 == 0 ))
    then
	echo "FizzBuzz"
    elif (( count % 5 == 0 ))
    then
        echo "Buzz"
    elif (( count % 3 == 0 ))
    then
        echo "Fizz"
    else
        echo "$count"
    fi
    (( count++ ))
done
