#!/usr/bin/env bash
# This script checks the file status
file="school"
if [ -e $file ]
then
    echo "school file exists"
    if [ -s $file ]
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
if [ -f $file ]
then
    echo "school is a regular file"
fi
