#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user j4ir0st/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
sudo -u nginx service nginx restart
